[package]
name = "interval-stabbing"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
arrayvec = "0.7.6"
itertools = "0.14.0"
nonmax = "0.5.5"
ordered-float = "5.0.0"
pyo3 = "0.24.2"

[dev-dependencies]
rand = "0.9.1"
